"""The operator's decisions on desk tickets. Append-only, and **not** trades.

Every press of a ticket button - Execute, Don't trade - and every expiry lands
here as one JSON line, attributed to the Discord user who pressed it. It is a
record of *judgement*: what the operator would and would not have taken.

What this file is not
---------------------
It is not the manual trading journal, and nothing here counts toward the
entry-3 gate in ``research/hypotheses.md``. That gate is pre-registered as
sixty rule-clean trades logged through ``journal/pretrade.py``, testing whether
the operator reading the tape has positive expectancy - and its own text says
the definition may only change by a dated addendum, never an edit. A click on
a signal generated by ``orb2``, a REJECTED strategy, is not that: the
mechanism was rejected, the thesis is the bot's, and a gate that counted
approved orb2 signals could be passed by an idea the log has already killed.

So ``journal/review.py`` *reports* these decisions in their own section and
leaves the 60-trade count alone. If the operator wants approvals to count,
the addendum comes first and the code change second.

Lives in ``journal/`` rather than ``bots/`` because both the desk and
``review.py`` read it, and ``review.py`` cannot import from ``bots/``.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
for _folder in ("strategies",):
    _p = str(PROJECT_ROOT / _folder)
    if _p not in sys.path:
        sys.path.insert(0, _p)

import rules  # noqa: E402

DECISIONS_PATH = PROJECT_ROOT / "journal" / "decisions.jsonl"

APPROVE = "approve"
DECLINE = "decline"
EXPIRED = "expired"
CHOICES = (APPROVE, DECLINE, EXPIRED)


@dataclass(frozen=True)
class Decision:
    """One operator decision on one ticket."""

    ticket_id: str
    strategy: str
    strategy_status: str
    mode: str
    decision: str
    user_id: int | None
    user_name: str
    decided_at: str
    instrument: str
    direction: str
    entry_price: float
    stop_price: float

    def __post_init__(self) -> None:
        if self.decision not in CHOICES:
            raise ValueError(f"decision must be one of {CHOICES}, got {self.decision!r}")

    def to_json(self) -> str:
        return json.dumps(asdict(self), default=str)


def append(record: Decision, path: Path = DECISIONS_PATH) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(record.to_json() + "\n")


def load(path: Path = DECISIONS_PATH) -> pd.DataFrame:
    """Every decision, oldest first. Empty frame when the file is absent."""
    path = Path(path)
    if not path.exists():
        return pd.DataFrame(columns=[f.name for f in Decision.__dataclass_fields__.values()])
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()]
    frame = pd.DataFrame(rows)
    if not frame.empty:
        frame["decided_at"] = pd.to_datetime(frame["decided_at"], utc=True).dt.tz_convert(rules.ET)
    return frame


def latest_per_ticket(frame: pd.DataFrame) -> pd.DataFrame:
    """One row per ticket: the last decision recorded for it.

    A ticket can carry more than one record - a decline followed by the
    expiry that fires anyway when the view times out. The *first* human
    decision is the one that matters for the record, so expiries never
    overwrite a click: they are kept only for tickets nobody decided on.
    """
    if frame.empty:
        return frame
    human = frame[frame["decision"] != EXPIRED]
    first_human = human.groupby("ticket_id", sort=False).head(1)
    undecided = frame[~frame["ticket_id"].isin(first_human["ticket_id"])]
    expiries = undecided[undecided["decision"] == EXPIRED].groupby(
        "ticket_id", sort=False).tail(1)
    return pd.concat([first_human, expiries]).sort_values("decided_at")


def summary(frame: pd.DataFrame) -> dict:
    latest = latest_per_ticket(frame)
    counts = latest["decision"].value_counts().to_dict() if not latest.empty else {}
    return {
        "tickets": int(len(latest)),
        "approved": int(counts.get(APPROVE, 0)),
        "declined": int(counts.get(DECLINE, 0)),
        "expired": int(counts.get(EXPIRED, 0)),
        "by_strategy": (latest.groupby(["strategy", "decision"]).size().to_dict()
                        if not latest.empty else {}),
    }


def format_decisions(path: Path = DECISIONS_PATH) -> str:
    """The review.py section. Reports; does not count toward anything."""
    line = "=" * 88
    out = [line, "OPERATOR DECISIONS ON DESK TICKETS (journal/decisions.jsonl)", line]
    frame = load(path)
    if frame.empty:
        out.append("  No decisions recorded yet.")
    else:
        s = summary(frame)
        out += [
            f"  Tickets decided     {s['tickets']}",
            f"    approved          {s['approved']}",
            f"    declined          {s['declined']}",
            f"    expired unpressed {s['expired']}",
        ]
        if s["by_strategy"]:
            out.append("")
            out.append("  By strategy:")
            for (strategy, decision), n in sorted(s["by_strategy"].items()):
                out.append(f"    {strategy:<22} {decision:<9} {n}")
        latest = latest_per_ticket(frame).tail(10)
        out.append("")
        out.append("  Most recent:")
        for _, r in latest.iterrows():
            when = pd.Timestamp(r["decided_at"]).strftime("%Y-%m-%d %H:%M")
            out.append(
                f"    {when}  {r['decision']:<8} {r['strategy']:<12} "
                f"{str(r['direction']).upper():<5} {r['instrument']} "
                f"@ {float(r['entry_price']):,.2f}  ({r['strategy_status']})"
                f"  by {r['user_name']}"
            )
    out += [
        "",
        "  These are a record of judgement, not trades. They do NOT count toward",
        "  the entry-3 gate above: that gate is pre-registered as trades logged",
        "  through pretrade.py, and changing it needs a dated addendum to",
        "  research/hypotheses.md entry 3 before any code counts them.",
    ]
    return "\n".join(out)
